language: node_js
node_js: stable

git:
  submodules: false

script: echo skip
script:
  - npm run lint
  - npm test

addons:
  hosts:
    - web-platform.test
    - www.web-platform.test
    - www1.web-platform.test
    - www2.web-platform.test
    - xn--n8j6ds53lwwkrqhv28a.web-platform.test
    - xn--lve-6lad.web-platform.test

matrix:
  include:
    - env: TEST_SUITE=node-canvas
      script: "export CXX=g++-4.8 && npm i canvas && npm test"
      addons:
        hosts:
          - web-platform.test
          - www.web-platform.test
          - www1.web-platform.test
          - www2.web-platform.test
          - xn--n8j6ds53lwwkrqhv28a.web-platform.test
          - xn--lve-6lad.web-platform.test
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - libcairo2-dev
            - libjpeg8-dev
            - libpango1.0-dev
            - libgif-dev
            - build-essential
    - env: TEST_SUITE=browser
      # Normally, travis runs your script in a docker container.
      # I've had firefox crash in docker containers (firefox tries to use linux namespaces, just like docker)
      # "sudo: required" causes travis to use a VM instead.
      sudo: required
      dist: trusty
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-mozilla-daily/firefox-aurora
        - sudo apt-get -qq update
        - sudo apt-get install -y xvfb openbox firefox
      script:
        - lsb_release -a
        - /usr/lib/firefox/firefox.sh --version
        - Xvfb :100 -ac -noreset -screen 0 1024x768x16 &
        - export DISPLAY=:100.0
        # Firefox can crash if you do not have a window manager
        # (for example when window.open() tries to maximize the new window)
        - openbox &
        - export FIREFOX_BIN=/usr/lib/firefox/firefox.sh
        - npm run pretest
        - npm run test-browser
